/* CSDA backup, encryption, integrity, normalization, and merge engine. */
function crc32Bytes(bytes){var c=-1;for(var i=0;i<bytes.length;i++){c^=bytes[i];for(var k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^-1)>>>0;}
function csvCell(v){return '"'+String(v==null?'':v).replace(/"/g,'""')+'"';}
function zipCSVFiles(files){var enc=new TextEncoder(),parts=[],central=[],offset=0;function u16(n){return new Uint8Array([n&255,n>>>8&255]);}function u32(n){return new Uint8Array([n&255,n>>>8&255,n>>>16&255,n>>>24&255]);}files.forEach(function(f){var name=enc.encode(f.name),data=enc.encode(f.text),crc=crc32Bytes(data),local=[u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),name,data],size=local.reduce(function(a,b){return a+b.length;},0);parts=parts.concat(local);central.push({name:name,crc:crc,size:data.length,offset:offset});offset+=size;});var cstart=offset;central.forEach(function(x){var a=[u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(x.crc),u32(x.size),u32(x.size),u16(x.name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(x.offset),x.name];parts=parts.concat(a);offset+=a.reduce(function(n,b){return n+b.length;},0);});parts.push(u32(0x06054b50),u16(0),u16(0),u16(central.length),u16(central.length),u32(offset-cstart),u32(cstart),u16(0));return new Blob(parts,{type:'application/zip'});}
function zipEntries(buffer){var b=new Uint8Array(buffer),dv=new DataView(buffer),p=0,dec=new TextDecoder(),out={};while(p+30<b.length&&dv.getUint32(p,true)===0x04034b50){var method=dv.getUint16(p+8,true),size=dv.getUint32(p+18,true),nl=dv.getUint16(p+26,true),xl=dv.getUint16(p+28,true),name=dec.decode(b.slice(p+30,p+30+nl)),start=p+30+nl+xl;if(method!==0)throw new Error('Compressed ZIP entries are unsupported');out[name]=dec.decode(b.slice(start,start+size));p=start+size;}return out;}
async function validateNormalizedZIP(buffer){var entries=zipEntries(buffer),manifest=entries['manifest.csv'];if(!manifest)throw new Error('manifest.csv not found');var rows=parseCSV(manifest);if(!rows.length||rows[0].indexOf('sha256')<0)throw new Error('Manifest has no integrity hashes');var fi=rows[0].indexOf('file'),hi=rows[0].indexOf('sha256');for(var i=1;i<rows.length;i++){var name=rows[i][fi],expected=rows[i][hi];if(!entries[name])throw new Error(name+' is missing');if((await sha256Text(entries[name]))!==expected)throw new Error(name+' failed integrity verification');}var er=parseCSV(entries['enrollments.csv']||''),ids={};for(var e=1;e<er.length;e++)ids[er[e][0]]=1;['enrollment_courses.csv','schedules.csv','payments.csv','refunds.csv','trainer_assignments.csv','completion_audits.csv','audit_events.csv'].forEach(function(fn){var rows=parseCSV(entries[fn]||'');for(var r=1;r<rows.length;r++)if(rows[r][1]&&!ids[rows[r][1]])throw new Error(fn+' contains a broken enrollment reference');});return entries;}
function zipFirstCSV(buffer,wanted){var b=new Uint8Array(buffer),dv=new DataView(buffer),p=0,dec=new TextDecoder();while(p+30<b.length&&dv.getUint32(p,true)===0x04034b50){var method=dv.getUint16(p+8,true),size=dv.getUint32(p+18,true),nl=dv.getUint16(p+26,true),xl=dv.getUint16(p+28,true),name=dec.decode(b.slice(p+30,p+30+nl)),start=p+30+nl+xl;if(name===wanted){if(method!==0)throw new Error('Compressed ZIP entries are unsupported');return dec.decode(b.slice(start,start+size));}p=start+size;}throw new Error(wanted+' not found');}
function downloadBlobFile(filename,blob){try{var a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;document.body.appendChild(a);a.click();setTimeout(function(){URL.revokeObjectURL(a.href);a.remove();},0);return true;}catch(e){return false;}}
var secureBackupPreview=null, secureBackupFileText='',secureBackupIntegrity='';
function bytesToB64(bytes){var out='',step=32768;for(var i=0;i<bytes.length;i+=step)out+=String.fromCharCode.apply(null,bytes.subarray(i,i+step));return btoa(out);}
function b64ToBytes(text){var raw=atob(text),out=new Uint8Array(raw.length);for(var i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out;}
function credentialConfigured(){return !!(DB.cfg&&DB.cfg.auth&&DB.cfg.auth.passwordVerifier);}
function passwordPolicy(p){if(!p||p.length<12)return 'Use at least 12 characters.';if(!/[A-Za-z]/.test(p)||!/[0-9]/.test(p))return 'Include at least one letter and one number.';if(p.toLowerCase()==='csda2026')return 'The legacy default cannot be reused.';return '';}
async function credentialVerifier(secret,salt,iterations){
  if(!window.crypto||!crypto.subtle)throw new Error('Secure credential functions are unavailable in this browser');
  var base=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),'PBKDF2',false,['deriveBits']);
  var bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:salt,iterations:iterations||210000,hash:'SHA-256'},base,256);
  return new Uint8Array(bits);
}
function secureBytesEqual(a,b){if(a.length!==b.length)return false;var d=0;for(var i=0;i<a.length;i++)d|=a[i]^b[i];return d===0;}
async function verifyCredential(secret,kind){var a=DB.cfg&&DB.cfg.auth;if(!a)return false;var salt=a[kind==='recovery'?'recoverySalt':'passwordSalt'],value=a[kind==='recovery'?'recoveryVerifier':'passwordVerifier'];if(!salt||!value)return false;var got=await credentialVerifier(secret,b64ToBytes(salt),a.iterations||210000);return secureBytesEqual(got,b64ToBytes(value));}
async function verifyAdministratorPassword(password){if(credentialConfigured())return verifyCredential(password,'password');return password===(DB.cfg.pwd||'csda2026');}
function newRecoveryKey(){var b=crypto.getRandomValues(new Uint8Array(20)),hex=Array.from(b).map(function(x){return x.toString(16).padStart(2,'0').toUpperCase();}).join('');return 'CSDA-'+hex.match(/.{1,5}/g).join('-');}
async function configureAdministratorCredential(password,recoveryKey,legacy){var iterations=210000,ps=crypto.getRandomValues(new Uint8Array(16)),rs=crypto.getRandomValues(new Uint8Array(16)),pv=await credentialVerifier(password,ps,iterations),rv=await credentialVerifier(recoveryKey,rs,iterations),now=new Date().toISOString();DB.cfg.auth={version:1,algorithm:'PBKDF2-SHA256',iterations:iterations,passwordSalt:bytesToB64(ps),passwordVerifier:bytesToB64(pv),recoverySalt:bytesToB64(rs),recoveryVerifier:bytesToB64(rv),createdAt:(DB.cfg.auth&&DB.cfg.auth.createdAt)||now,changedAt:now,legacyMigratedAt:legacy?now:((DB.cfg.auth&&DB.cfg.auth.legacyMigratedAt)||'')};delete DB.cfg.pwd;}
async function changeAdministratorPassword(current,next){if(!(await verifyAdministratorPassword(current)))throw new Error('Current Administrator password is incorrect.');var err=passwordPolicy(next);if(err)throw new Error(err);var a=DB.cfg.auth,ps=crypto.getRandomValues(new Uint8Array(16)),pv=await credentialVerifier(next,ps,a.iterations||210000);a.passwordSalt=bytesToB64(ps);a.passwordVerifier=bytesToB64(pv);a.changedAt=new Date().toISOString();}

async function backupKey(password,salt,usage){
  var base=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);
  return crypto.subtle.deriveKey({name:'PBKDF2',salt:salt,iterations:210000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,[usage]);
}
async function encryptBackupValue(value,password){
  var salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await backupKey(password,salt,'encrypt'),clear=new TextEncoder().encode(typeof value==='string'?value:JSON.stringify(value)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv:iv},key,clear);
  return JSON.stringify({format:'csda-field-aes-gcm',version:1,iterations:210000,salt:bytesToB64(salt),iv:bytesToB64(iv),data:bytesToB64(new Uint8Array(cipher))});
}
async function sha256Text(text){var h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return Array.from(new Uint8Array(h)).map(function(x){return x.toString(16).padStart(2,'0');}).join('');}
async function normalizedBackupFiles(password){
  var files=[],media=[],mediaRows=[],addTable=async function(name,headers,rows){var lines=[headers.join(',')];for(var i=0;i<rows.length;i++){var r=rows[i],fixed=r.slice(0,headers.length-1),payload=await encryptBackupValue(r[headers.length-1],password);lines.push(fixed.map(csvCell).concat(csvCell(payload)).join(','));}files.push({name:name,text:lines.join('\r\n')+'\r\n'});};
  var recs=DB.records||[],students=[],contacts=[],enrollments=[],ec=[],schedules=[],payments=[],refunds=[],ta=[],audits=[],events=[];
  for(var i=0;i<recs.length;i++){var r=recs[i],ref=r.ref||('record-'+i),studentId=ref+'-student';students.push([studentId,{student:r.student||{}}]);contacts.push([ref+'-contact',studentId,{guardian:r.guardian||{},consent:r.consent||{}}]);enrollments.push([ref,studentId,{date:r.date,status:r.enrollmentStatus||'active',totals:r.totals||{},plan:r.plan||'',promos:r.promos||[]}]);(r.courses||[]).forEach(function(id,n){ec.push([ref+'-'+n,ref,id,{position:n}]);});schedules.push([ref+'-schedule',ref,{schedule:r.sched||{},completedHours:r.completedHours||0,timelineOverride:r.timelineOverride||null}]);
    for(var j=0;j<(r.payments||[]).length;j++){var pm=JSON.parse(JSON.stringify(r.payments[j])),mid='media/payment-receipts/'+ref+'-'+j+'.enc';if(pm.receipt){media.push({name:mid,text:await encryptBackupValue(pm.receipt,password)});mediaRows.push([mid,ref,'payment_receipt',{paymentIndex:j}]);delete pm.receipt;}payments.push([ref+'-payment-'+j,ref,mid,pm]);}
    var cert=JSON.parse(JSON.stringify(r.certification||{})),fin=cert.financial||{},rmid='';if(fin.refundReceipt){rmid='media/refund-receipts/'+ref+'.enc';media.push({name:rmid,text:await encryptBackupValue(fin.refundReceipt,password)});mediaRows.push([rmid,ref,'refund_receipt',{}]);delete fin.refundReceipt;}refunds.push([ref+'-refund',ref,rmid,fin]);ta.push([ref+'-trainers',ref,{primary:r.trainer||{},assignments:r.trainerAssignments||[]}]);audits.push([ref+'-audit',ref,{certification:cert,changes:r.completionAuditChanges||[]}]);(r.operationalHistory||[]).forEach(function(x,n){events.push([ref+'-event-'+n,ref,x]);});
  }
  await addTable('students.csv',['student_id','payload'],students);await addTable('contacts.csv',['contact_id','student_id','payload'],contacts);await addTable('enrollments.csv',['enrollment_id','student_id','payload'],enrollments);await addTable('enrollment_courses.csv',['row_id','enrollment_id','course_id','payload'],ec);await addTable('schedules.csv',['schedule_id','enrollment_id','payload'],schedules);await addTable('payments.csv',['payment_id','enrollment_id','media_path','payload'],payments);await addTable('refunds.csv',['refund_id','enrollment_id','media_path','payload'],refunds);await addTable('trainer_assignments.csv',['assignment_id','enrollment_id','payload'],ta);await addTable('completion_audits.csv',['audit_id','enrollment_id','payload'],audits);await addTable('audit_events.csv',['event_id','enrollment_id','payload'],events);
  var trainers=[],items=[];for(var ti=0;ti<(DB.trainers||[]).length;ti++){var tx=JSON.parse(JSON.stringify(DB.trainers[ti])),tp='';if(tx.photo){tp='media/trainer-photos/'+(tx.id||('trainer-'+ti))+'.enc';media.push({name:tp,text:await encryptBackupValue(tx.photo,password)});mediaRows.push([tp,tx.id||'','trainer_photo',{}]);delete tx.photo;}tx.photoMediaPath=tp;trainers.push(tx);}for(var ci=0;ci<(DB.items||[]).length;ci++){var ix=JSON.parse(JSON.stringify(DB.items[ci]));for(var ak of ['art','artFull'])if(ix[ak]){var ap='media/course-artwork/'+(ix.id||('course-'+ci))+'-'+ak+'.enc';media.push({name:ap,text:await encryptBackupValue(ix[ak],password)});mediaRows.push([ap,ix.id||'','course_'+ak,{}]);delete ix[ak];ix[ak+'MediaPath']=ap;}items.push(ix);}var catalogue=await encryptBackupValue({items:items,cats:DB.cats||[],promos:DB.promos||[],plans:DB.plans||[],holidays:DB.holidays||[],facility:DB.facility||{},units:DB.units||[],trainers:trainers},password);files.push({name:'catalogue.csv',text:'format,payload\r\n'+csvCell('csda-normalized-catalogue')+','+csvCell(catalogue)+'\r\n'});
  await addTable('catalogue_courses.csv',['course_id','payload'],items.map(function(x){return [x.id||'',x];}));await addTable('trainers.csv',['trainer_id','payload'],trainers.map(function(x){return [x.id||'',x];}));await addTable('promotions.csv',['promotion_id','payload'],(DB.promos||[]).map(function(x){return [x.id||'',x];}));await addTable('payment_plans.csv',['plan_id','payload'],(DB.plans||[]).map(function(x){return [x.id||'',x];}));await addTable('facility_records.csv',['facility_id','payload'],[['facility',DB.facility||{}]].concat((DB.rentals||[]).map(function(x){return [x.ref||x.id||'',x];})));await addTable('media_index.csv',['media_path','parent_id','media_type','payload'],mediaRows);files=files.concat(media);
  return files;
}
async function normalizedManifest(files,stamp){var lines=['file,type,encrypted,sha256,exported_at,schema_version'];for(var i=0;i<files.length;i++)lines.push([files[i].name,files[i].name.indexOf('media/')===0?'referenced_media':'related_csv','yes',await sha256Text(files[i].text),stamp,'1'].map(csvCell).join(','));return lines.join('\r\n')+'\r\n';}
async function encryptFullBackup(password){
  if(!window.crypto||!crypto.subtle)throw new Error('Secure encryption is unavailable in this browser');
  var salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12));
  var key=await backupKey(password,salt,'encrypt'),stamp=new Date().toISOString();
  var payload={format:'csda-toolkit-session',version:2,exportedAt:stamp,catalogueVersion:DB.catalogueVersion||'',data:DB};
  var cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv:iv},key,new TextEncoder().encode(JSON.stringify(payload)));
  return {stamp:stamp,text:JSON.stringify({format:'csda-toolkit-encrypted-backup',version:1,kdf:'PBKDF2-SHA256',iterations:210000,cipher:'AES-256-GCM',salt:bytesToB64(salt),iv:bytesToB64(iv),data:bytesToB64(new Uint8Array(cipher))})};
}
async function decryptFullBackup(text,password){
  var env=JSON.parse(text);if(!env||env.format!=='csda-toolkit-encrypted-backup')throw new Error('Not an encrypted CSDA session backup');
  var key=await backupKey(password,b64ToBytes(env.salt),'decrypt');
  var clear=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64ToBytes(env.iv)},key,b64ToBytes(env.data));
  var payload=JSON.parse(new TextDecoder().decode(clear));
  if(!payload||payload.format!=='csda-toolkit-session'||!payload.data||!payload.data.items||!payload.data.cats)throw new Error('Backup contents are incomplete');
  return payload;
}
function backupSummary(payload){var d=payload.data||{};return {courses:(d.items||[]).length,students:(d.records||[]).length,trainers:(d.trainers||[]).length,promos:(d.promos||[]).length,rentals:(d.rentals||[]).length,exportedAt:payload.exportedAt||''};}
function mergeByKey(local,incoming,keys){var out=(local||[]).slice();(incoming||[]).forEach(function(x){var ix=out.findIndex(function(y){return keys.some(function(k){return x[k]!=null&&y[k]===x[k];});});if(ix<0)out.push(x);else out[ix]=x;});return out;}
function recordModifiedAt(r){var dates=[r.updatedAt,r.finalizedAt,((r.certification||{}).admin||{}).at].concat((r.operationalHistory||[]).map(function(x){return x.at;}),(r.completionAuditChanges||[]).map(function(x){return x.at;})).filter(Boolean).sort();return dates[dates.length-1]||'';}
function mergeNewestRecords(local,incoming){var map={};(local||[]).forEach(function(r){map[r.ref]=JSON.parse(JSON.stringify(r));});(incoming||[]).forEach(function(r){var old=map[r.ref];if(!old){map[r.ref]=r;return;}var winner=recordModifiedAt(r)>recordModifiedAt(old)?JSON.parse(JSON.stringify(r)):old,combined=(old.operationalHistory||[]).concat(r.operationalHistory||[]),seen={};winner.operationalHistory=combined.filter(function(x){var k=(x.at||'')+'|'+(x.kind||'')+'|'+(x.note||'');if(seen[k])return false;seen[k]=1;return true;}).sort(function(a,b){return String(a.at||'').localeCompare(String(b.at||''));});map[r.ref]=winner;});return Object.keys(map).map(function(k){return map[k];});}
function mergeBackupData(incoming){
  var merged=JSON.parse(JSON.stringify(DB)), arrays={items:['id','code'],cats:['id'],trainers:['id'],promos:['id'],plans:['id'],holidays:['d'],rentals:['ref','id'],units:['id'],audit:['at']};
  Object.keys(incoming).forEach(function(k){if(k==='records')merged.records=mergeNewestRecords(merged.records,incoming.records);else if(arrays[k])merged[k]=mergeByKey(merged[k],incoming[k],arrays[k]);else if(k==='cfg'||k==='pay')merged[k]=Object.assign({},merged[k]||{},incoming[k]||{});else if(!Array.isArray(incoming[k]))merged[k]=incoming[k];});
  /* Imports keep the receiving installation's credential; backup passwords only decrypt backup contents. */
  if(DB.cfg&&merged.cfg){merged.cfg.auth=DB.cfg.auth;delete merged.cfg.pwd;}
  return merged;
}
function applySecureBackup(mode){
  if(!secureBackupPreview)return;var payload=secureBackupPreview,summary=backupSummary(payload);
  var receivingAuth=DB.cfg&&DB.cfg.auth;DB=mode==='merge'?mergeBackupData(payload.data):JSON.parse(JSON.stringify(payload.data));migrateDB();if(receivingAuth){DB.cfg.auth=receivingAuth;delete DB.cfg.pwd;}save();
  store.set('csda_backup_at',payload.exportedAt||new Date().toISOString());store.set('csda_backup_changes','0');try{localStorage.removeItem('csda_restore_recommended');}catch(e){delete mem.csda_restore_recommended;}
  logAction((mode==='merge'?'Merged':'Restored')+' encrypted session backup containing '+summary.students+' enrollments',staffName);save();secureBackupPreview=null;buildDir();renderFeed();renderAdmin();toast(mode==='merge'?'Backup merged with this app':'Complete app session restored');
}

